language: r
warnings_are_errors: true
cache: packages
bioc_required: true
cran: http://cran.rstudio.com
dist: trusty
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libxml2-dev
    - libfftw3-dev
    - libgsl0-dev
    - mesa-common-dev
    - libglu1-mesa-dev
    - devscripts
    - jags
os:
- linux
- osx
osx_image: xcode9.4
services: xvfb
r:
- 3.3
- 3.4
- 3.5
- release
- devel
jobs:
  allow_failures:
  - r: devel
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=oslerinhealth
  - DISPLAY=:99.0
  - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
  - _R_CHECK_FORCE_SUGGESTS_=false
  - CACHE_NAME="${TRAVIS_OS_NAME}-R-${TRAVIS_R_VERSION}"
r_check_args: "--as-cran --install-args=--build"
before_install:
- if [ "$TRAVIS_DIST" = "trusty" ]; then sudo apt-get -y install libgsl0ldbl ; fi
- ulimit -n 2048
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- codename=`linux_codename`;
- start_xvfb ;
- export rver=`r_version`; echo $rver ;
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then no_open_mp ; brew install -v freetype ; fi
- jags_install || true;
- if `need_v8`; then v8_install || true; fi
- dcmtk_install || true;
- gsl_install 2.1 || true ;
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- echo "Package Name is $PACKAGE_NAME"
- setup_python 3.6 false ;
- install_python_requirements ;
after_success: dump_logs
after_failure: dump_logs
before_deploy:
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then PKG_TARBALL=$(ls -1t *.tgz | head -n 1);
  PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tgz/_'"R${rver}"'.tgz/'` ; mv ${PKG_TARBALL}
  ${PKG_TARBALL_WITH_R} ; echo "Built tarball is ${PKG_TARBALL_WITH_R}" ; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then PKG_TARBALL=$(ls -1t *.tar.gz | head -n
  1); PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tar.gz/_'"R${rver}"'.tar.gz/'`
  ; mv ${PKG_TARBALL} ${PKG_TARBALL_WITH_R} ; echo "Built tarball is ${PKG_TARBALL_WITH_R}"
  ; fi
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  token:
    secure: fakekey
  file_glob: true
  overwrite: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: HvWqr6Y8r4noEjRJoZExLkCNJxUyQKspCEBvCvPTHt6bXJwXQkiRmmGK/yfRYU66+nnV+iHXBc2SNkXG8+P7fE6KG9JhVw6HsJyikgi3AfsZHRF41wk7o77r1QcX1gAQj9RnoAZhc6azdBeGSbHdb8n6HDZq5LJBRdgc66UXgN/heSyVsIyzLsB2g/zI4bIdxjSZkFwY4SkAj/hsfbGrs9pm+fpeBDe87EZdzTm3G8SrcsXPH9rVLI2MDLrLVDyEJwO7kEPsQMwrmLrAXs6B/gYtUTErPQ+L+wvv5G2+s92mOlhugW3+v/HCbfeWqQCuqS7xluFg4nM36SRKBjH/kU7KJhy3YLOivmJYGVYN87eVE9p5S1ZFt9mLRh5M7wipOJcSKLd2MLoFXaQo7zN+bIGOTCPNxP9Adxy4XD81BpMCzRRn4OZ8lgUZQW5RO9aZN0xWAbI5k7iV53BjTtS01mXZEEcXSHcRLuJT/eHk48EfO7FW+vyirCIRd74IbXvmn2RgCYkrtav4aWns6vFdPF6QdtVLSl5n2Wqy7YyGr/LmT/oHqJ1y1L/vs8bUOg5fysJdRXicEgBXfXoA0nTtDQYEG0AzwRLFUKZekbiZ+Zw39pItLeATz1WsqUV7FUVm/pqo2CU6+ywk6i+1Bh4jnssUIGTrePKPK/30DEUb7ho=
after_deploy:
- echo "${PROJECT_NAME}" | grep -q "releases"; if [[ $? -eq 0 ]]; then run_coverage="false";
  else run_coverage=; fi;
- if [[ "${TRAVIS_OS_NAME}" == "linux" && ${TRAVIS_R_VERSION_STRING} = "release" &&
  -z "${run_coverage}" ]]; then echo 'covr::coveralls(type = "all", quiet = FALSE)'
  > osler_covr.R ; travis_wait 100 Rscript osler_covr.R ; rm osler_covr.R ; fi

#neuroc.deps version (SHA): b15fd0b