language: r
warnings_are_errors: false
cache: false
bioc_required: true
cran: http://cran.rstudio.com
dist: trusty
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libxml2-dev
    - libfftw3-dev
    - libgsl0-dev
    - devscripts
os:
- linux
- osx
services: xvfb
r: release
env:
  global:
  - R_BUILD_ARGS="--no-manual"
  - R_CHECK_ARGS="--as-cran --install-args=--build"
  - RGL_USE_NULL=TRUE
  - WARNINGS_ARE_ERRORS=1
  - PROJECT_NAME=oslerinhealth
  - DISPLAY=:99.0
  - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
  - _R_CHECK_FORCE_SUGGESTS_=false
  - secure: LnsKl2JF+2U22S1taY4decAGMeRRFceA8J6Rnkf4V/TE2MEbdQu6MHdaQLVbbeOTcS7ifHPo4grembL7Hi3IU59b/P/OvzfbnlPoybzW7Ln9O3XdXrVKB0K//cWHXlaBbB9nhJdbfw3IkxZcTkUaqkiB5S40CqGRC4pNLvd5yyTF9byLI/SR4FkRm8Ewi4ycRxTJA5eB3G2J3JIDET7b8hs7Jf5u2qH7McSnZH1kXCQ/JK5skw4lbUpxMIEV+/RwN7aXmMUA3ZgVlZ3LlKjjpgRk5ZBToxFsAoxj+IDfExlqnImac9UOEbSk3RooSjVjACyXB38laK4FKlkpRDzw8+Zd0QhvLH2U9RwXMPKQPGCvAA4emGpHO+7Is20na06nSo5c2WgeB8Dci1jhgVpGYpdCeU6j7LVjt5NqV3xBOwkvhOIWUNzaBp8yA+B3dfCUwPOqdkoQDb/SSiRh6jUIIE25SttvIddDweCvyY+UhXsZBQgDXVeJPxSfIxugrKmUigFLDGmQoKFWEEMANCioWAtbzY3c9us8186373E8+qyj/oQQzkAeTE0NsLVYCZ0hIhjrADgHomii5HKzZ1ZOlk2bD9mMXGcHiwqGM/6M0RHmaCZcI/RBSt97Qu4oXuNCwgBlb0WMVwV75fdSsls/FPlwMNBz1Ew9Ea2joW01NR4=
before_install:
- if [ "$TRAVIS_DIST" = "trusty" ]; then sudo apt-get -y install libgsl0ldbl ; fi
- ulimit -n 2048
- export LD_LIBRARY_PATH=/usr/local/clang/lib:${LD_LIBRARY_PATH}
- export PROJ_DIR=`basename $PWD`
- echo "travis_wait*\.log$" >> .Rbuildignore
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- codename=`linux_codename`;
- if [ "${codename}" = "trusty" ]; then start_xvfb ; fi
- jags_install || true;
- if `need_v8`; then v8_install || true; fi
- dcmtk_install || true;
- gsl_install 2.1 || true ;
- export rver=`r_version`; echo $rver ;
- export PACKAGE_NAME=`package_name`
- export RCHECK_DIR=${PACKAGE_NAME}.Rcheck
- remove_neuroc_packages
- export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=1
- x=`export_clang_cxx`; eval ${x}
- echo "CC=${CC}, CXX=${CXX}, CXX1X=${CXX1X}"
- echo "CXX1XSTD=${CXX1XSTD}, CXX11=${CXX11}"
- clang_cxx
- export cmake_version="3.11"
- cmake --version
- x=`cmake_setup`; echo "${x}"; eval ${x};
- cmake --version
- export ants_user=oslerinhealth
- if [[ "${PACKAGE_NAME}" == "ITKR" || "${PACKAGE_NAME}" == "ANTsRCore" || "${PACKAGE_NAME}"
  == "ANTsR" ]]; then Rscript -e "install.packages(c('Rcpp', 'RcppEigen'), type =
  'source', repo = 'http://cran.rstudio.com')" ; fi
- if [[ "${PACKAGE_NAME}" == "ITKR" || "${PACKAGE_NAME}" == "ANTsRCore" ]]; then export
  R_BUILD_ARGS="${R_BUILD_ARGS} --no-build-vignettes " ; export R_CHECK_ARGS="--no-vignettes
  ${R_CHECK_ARGS}" ; fi
- if [[ "${PACKAGE_NAME}" != "ITKR" ]]; then echo "Installing Missing Deps ITKR" ;
  install_missing_remote_deps_all ${ants_user}/ITKR ; gh_binary_install ${ants_user}/ITKR
  ; fi
- if [[ "${PACKAGE_NAME}" != "ANTsRCore" && "${PACKAGE_NAME}" != "ITKR" ]]; then echo
  "Installing Missing Deps ANTsRCore" ; install_missing_remote_deps_all ${ants_user}/ANTsRCore;
  gh_binary_install_passive ${ants_user}/ANTsRCore ; fi
- if [[ "${PACKAGE_NAME}" != "ANTsRCore" && "${PACKAGE_NAME}" != "ITKR" && "${PACKAGE_NAME}"
  != "ANTsR" ]]; then echo "Installing Missing Deps ANTsR" ; install_missing_remote_deps_all
  ${ants_user}/ANTsR ; gh_binary_install_passive ${ants_user}/ANTsR ; fi
- if [[ "${PACKAGE_NAME}" == "ANTsR" ]]; then export _R_CHECK_FORCE_SUGGESTS_=false
  ; fi
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- echo $PATH ;
- install_deps_no_suggests
- install_python_requirements ;
- R CMD javareconf ;
- travis_run_cache
script:
- Rscript -e 'install.packages("remotes")'
- Rscript -e 'remotes::install_github("hadley/pkgdown")'
- travis_wait 100 Rscript -e 'pkgdown::build_site()'
after_failure: 
before_deploy: 
deploy:
  provider: pages
  keep_history: true
  skip_cleanup: true
  local_dir: docs
  on:
    branch: master
  token: "$GITHUB_TOKEN"
after_deploy: 
