// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// get_ideal_resp
arma::mat get_ideal_resp(arma::mat Q, arma::mat Z);
RcppExport SEXP _slamR_get_ideal_resp(SEXP QSEXP, SEXP ZSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Q(QSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Z(ZSEXP);
    rcpp_result_gen = Rcpp::wrap(get_ideal_resp(Q, Z));
    return rcpp_result_gen;
END_RCPP
}
// bsxfun_7_pow
arma::cube bsxfun_7_pow(arma::mat A, arma::mat B);
RcppExport SEXP _slamR_bsxfun_7_pow(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::mat >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(bsxfun_7_pow(A, B));
    return rcpp_result_gen;
END_RCPP
}
// bsxfun_7_hinge_pow
arma::cube bsxfun_7_hinge_pow(arma::mat A, arma::mat B);
RcppExport SEXP _slamR_bsxfun_7_hinge_pow(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::mat >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(bsxfun_7_hinge_pow(A, B));
    return rcpp_result_gen;
END_RCPP
}
// bsxfun_7_hinge_pow_prod
arma::mat bsxfun_7_hinge_pow_prod(arma::mat A, arma::mat B);
RcppExport SEXP _slamR_bsxfun_7_hinge_pow_prod(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::mat >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(bsxfun_7_hinge_pow_prod(A, B));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_slamR_get_ideal_resp", (DL_FUNC) &_slamR_get_ideal_resp, 2},
    {"_slamR_bsxfun_7_pow", (DL_FUNC) &_slamR_bsxfun_7_pow, 2},
    {"_slamR_bsxfun_7_hinge_pow", (DL_FUNC) &_slamR_bsxfun_7_hinge_pow, 2},
    {"_slamR_bsxfun_7_hinge_pow_prod", (DL_FUNC) &_slamR_bsxfun_7_hinge_pow_prod, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_slamR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
